# Generated by Django 6.0.5 on 2026-06-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Aroma')),
                ('note_type', models.CharField(choices=[('TOP', 'Top Notes'), ('MIDDLE', 'Middle Notes'), ('BASE', 'Base Notes')], max_length=10, verbose_name='Tipe Note')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fragrance Note',
                'verbose_name_plural': 'Fragrance Notes',
                'ordering': ['note_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_notes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.fragrancenote', verbose_name='Fragrance Notes'),
        ),
    ]
