# Generated by Django 6.0.5 on 2026-06-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fragrancenote_product_fragrance_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ml', models.PositiveIntegerField(verbose_name='Ukuran (ml)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Harga')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Varian Produk',
                'verbose_name_plural': 'Varian Produk',
                'ordering': ['size_ml'],
                'unique_together': {('product', 'size_ml')},
            },
        ),
    ]
