# Generated by Django 6.0.5 on 2026-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_product_brand_productimage_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Keluarga Aroma')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Keluarga Aroma',
                'verbose_name_plural': 'Keluarga Aroma',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_families',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.fragrancefamily', verbose_name='Keluarga Aroma'),
        ),
    ]
