# Generated by Django 6.0.5 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender_target',
            field=models.CharField(choices=[('men', 'For Men'), ('women', 'For Women'), ('unisex', 'Unisex')], default='unisex', max_length=10, verbose_name='Target Gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='longevity',
            field=models.CharField(choices=[('short', '1–3 hours'), ('moderate', '3–6 hours'), ('long', '6–9 hours'), ('very_long', '9+ hours')], default='moderate', max_length=10, verbose_name='Daya Tahan'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('daily', 'Daily'), ('office', 'Office'), ('casual', 'Casual'), ('formal', 'Formal'), ('evening', 'Evening')], default='daily', max_length=10, verbose_name='Kesempatan'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], default='all', max_length=10, verbose_name='Musim'),
        ),
        migrations.AddField(
            model_name='product',
            name='sillage',
            field=models.CharField(choices=[('intimate', 'Intimate'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='moderate', max_length=10, verbose_name='Sillage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Komentar'),
        ),
    ]
