# Generated by Django 6.0.6 on 2026-06-23 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_product_morris_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='products_ca_name_693421_idx'),
        ),
        migrations.AddIndex(
            model_name='fragrancefamily',
            index=models.Index(fields=['name'], name='products_fr_name_dfa6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='fragrancenote',
            index=models.Index(fields=['note_type', 'name'], name='products_fr_note_ty_b3c81b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', '-created_at'], name='products_pr_is_avai_8299d1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='products_pr_categor_c898cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender_target'], name='products_pr_gender__7da410_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['occasion'], name='products_pr_occasio_1d5c78_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['season'], name='products_pr_season_b86906_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='products_re_created_351f12_idx'),
        ),
    ]
