# Generated by Django 6.0.5 on 2026-06-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_products_ca_name_693421_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug Lama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='products.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Redirect Slug',
                'verbose_name_plural': 'Redirect Slug',
                'ordering': ['-created_at'],
            },
        ),
    ]
