# Generated by Django 6.0.5 on 2026-06-15 22:49

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, editable=False, max_length=30, unique=True, verbose_name='Nomor Pesanan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total Harga')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Nama Penerima')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('shipping_address', models.TextField(verbose_name='Alamat Lengkap')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Kode Pos')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Pesanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Pesanan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Harga')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pesanan')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Item Pesanan',
                'verbose_name_plural': 'Item Pesanan',
            },
        ),
    ]
