# Generated by Django 6.0.5 on 2026-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Varian'),
        ),
    ]
