# Generated by Django 6.0.5 on 2026-06-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Voucher')),
                ('discount_type', models.CharField(choices=[('percentage', 'Persen (%)'), ('fixed', 'Nominal (Rp)')], default='percentage', max_length=20, verbose_name='Tipe Diskon')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Nilai Diskon')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, help_text='Total belanja minimum sebelum diskon', max_digits=12, verbose_name='Min. Belanja')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='Maksimal nominal diskon (khusus persen)', max_digits=12, null=True, verbose_name='Maks. Diskon')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Maks. Penggunaan')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Sudah Digunakan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('valid_from', models.DateTimeField(verbose_name='Berlaku Dari')),
                ('valid_until', models.DateTimeField(verbose_name='Berlaku Sampai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Diskon'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.voucher', verbose_name='Voucher'),
        ),
    ]
