# Generated by Django 6.0.6 on 2026-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orders_orde_user_id_0ae59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
    ]
