# Generated by Django 6.0.5 on 2026-06-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_brand_product_brand_productimage_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Label')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Nama Penerima')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Kode Pos')),
                ('is_default', models.BooleanField(default=False, verbose_name='Alamat Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Alamat Pelanggan',
                'verbose_name_plural': 'Alamat Pelanggan',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product', verbose_name='Produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='products.productvariant', verbose_name='Varian')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlist',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product', 'variant')},
            },
        ),
    ]
