# Generated by Django 6.0.5 on 2026-06-16 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wishlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=20, verbose_name='Level')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Total Poin')),
                ('total_spending', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total Belanja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profile',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Poin')),
                ('type', models.CharField(choices=[('EARN', 'Earned'), ('REDEEM', 'Redeemed'), ('UPGRADE', 'Level Upgrade')], max_length=10, verbose_name='Tipe')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Transaksi Poin',
                'verbose_name_plural': 'Transaksi Poin',
                'ordering': ['-created_at'],
            },
        ),
    ]
