# Generated by Django 6.0.6 on 2026-06-23 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_memberprofile_pointtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['level'], name='accounts_me_level_4a7ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='accounts_po_user_id_67ec0e_idx'),
        ),
    ]
