# Generated by Django 6.0.6 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_memberprofile_accounts_me_level_4a7ccd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
    ]
