# Generated by Django 6.0.6 on 2026-06-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_migrate_profile_to_customeraddress'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='address',
            new_name='address_line',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='regions.district', verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='rt',
            field=models.CharField(blank=True, max_length=4, verbose_name='RT'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='rw',
            field=models.CharField(blank=True, max_length=4, verbose_name='RW'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='regions.city', verbose_name='Kota/Kabupaten'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='regions.postalcode', verbose_name='Kode Pos'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='regions.province', verbose_name='Provinsi'),
        ),
    ]
