# Generated by Django 6.0.6 on 2026-06-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Kode Kota')),
                ('name', models.CharField(max_length=100, verbose_name='Kota/Kabupaten')),
            ],
            options={
                'verbose_name': 'Kota/Kabupaten',
                'verbose_name_plural': 'Kota/Kabupaten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Kode Provinsi')),
                ('name', models.CharField(max_length=100, verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Kode Kecamatan')),
                ('name', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='regions.city', verbose_name='Kota/Kabupaten')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Kode Pos')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='regions.district', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kode Pos',
                'verbose_name_plural': 'Kode Pos',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regions.province', verbose_name='Provinsi'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['city'], name='regions_dis_city_id_fca983_idx'),
        ),
        migrations.AddIndex(
            model_name='postalcode',
            index=models.Index(fields=['district'], name='regions_pos_distric_8e6df0_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='regions_cit_provinc_d04a79_idx'),
        ),
    ]
