# Generated by Django 6.0.5 on 2026-06-16 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Voucher')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('discount_type', models.CharField(choices=[('percentage', 'Persen (%)'), ('fixed', 'Nominal (Rp)')], default='percentage', max_length=20, verbose_name='Tipe Diskon')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Nilai Diskon')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, help_text='Total belanja minimum sebelum diskon', max_digits=12, verbose_name='Min. Belanja')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='Maksimal nominal diskon (khusus persen)', max_digits=12, null=True, verbose_name='Maks. Diskon')),
                ('expired_date', models.DateField(blank=True, help_text='Setelah tanggal ini, voucher tidak bisa digunakan', null=True, verbose_name='Tanggal Kedaluwarsa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voucher Promosi',
                'verbose_name_plural': 'Voucher Promosi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('used', 'Terpakai'), ('expired', 'Kedaluwarsa')], default='available', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditugaskan Pada')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Digunakan Pada')),
                ('expires_at', models.DateTimeField(verbose_name='Kedaluwarsa Pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='promotions.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Voucher Pengguna',
                'verbose_name_plural': 'Voucher Pengguna',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
