# Generated by Django 6.0.5 on 2026-06-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID Transaksi Midtrans')),
                ('snap_token', models.CharField(blank=True, max_length=255, verbose_name='Snap Token')),
                ('snap_redirect_url', models.URLField(blank=True, verbose_name='Snap Redirect URL')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Metode Pembayaran')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Jumlah')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('fraud_status', models.CharField(blank=True, max_length=50, verbose_name='Fraud Status')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Pembayaran')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Response Midtrans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Pesanan')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
    ]
