# Generated by Django 6.0.5 on 2026-06-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status Sebelumnya')),
                ('to_status', models.CharField(max_length=20, verbose_name='Status Baru')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Response Midtrans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.payment', verbose_name='Pembayaran')),
            ],
            options={
                'verbose_name': 'Riwayat Status Pembayaran',
                'verbose_name_plural': 'Riwayat Status Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
    ]
