# Generated by Django 6.0.6 on 2026-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orders_orde_user_id_0ae59f_idx_and_more'),
        ('payments', '0002_paymentstatushistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
